query getRooms($input: GetRoomsIntput!) {
	getRooms(input: $input) {
		data {
			id
			capacity
			description
			language
      		topic
			clients {
				id
				avatar
				username
			}
			creator {
				id
				avatar
				username
			}
		}
		pagination {
			limit
			page
			totalCount
		}
	}
}
